name: Install and Auto-release DTO-lib

on:
  push:
    branches: [master]

permissions:
  contents: write
  packages: write

jobs:
  test-install-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: Build and install
        run: mvn clean install -B
        working-directory: ./lna-ai-integration-dto

      - name: Get version from pom.xml
        id: get_version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        working-directory: ./lna-ai-integration-dto

      - name: Configure Git for tagging
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Tag current version
        run: |
          git tag -a "v${{ env.VERSION }}" -m "Release v${{ env.VERSION }}"
          git push origin "v${{ env.VERSION }}"

      - name: Deploy to GitHub Packages
        run: mvn deploy -B -DskipTests
        working-directory: ./lna-ai-integration-dto
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}